name: jmeter-ci-performance-test

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  jmeter-ci:
    runs-on: ubuntu-latest

    steps:
    # Checkout source code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Build custom Docker image
    - name: Build custom JMeter Docker image
      run: docker build -t custom-jmeter .

    # Run JMeter test from your custom image
    - name: Run JMeter test in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/jmeter \
          -e JVM_ARGS="-Xms1g -Xmx1g" \
          custom-jmeter \
          jmeter -n \
                 -t /jmeter/DevCon-Demo-Script_v2.jmx \
                 -l /jmeter/results/results.jtl \
                 -e -o /jmeter/results/html \
                 -p /jmeter/user.properties \
                 -j /jmeter/results/jmeter.log \
                 -Jjmeter.save.saveservice.output_format=csv

    # Upload HTML Report (new action version )
    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-html-report
        path: results/html

    # Upload raw JTL Results
    - name: Upload Raw Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-jtl-results
        path: results/results.jtl

    # Deploy to GitHub Pages
    - name: Deploy report to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: jmeter/results/html
